# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master

pool:
  name: 'MyLocalAgent'

variables:
  buildConfiguration: 'Release'

steps:
# 1) Restore
- script: dotnet restore TaskManager/TaskManager.csproj
  displayName: 'Restore NuGet packages'

# 2) Build
- script: dotnet build TaskManager/TaskManager.csproj -c $(buildConfiguration) --no-restore
  displayName: 'Build project'

# 3) Test (se vuoi, altrimenti togli questo step)
- script: dotnet test TaskManager/TaskManager.csproj -c $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run tests'

# 4) Publish
- script: dotnet publish TaskManager/TaskManager.csproj -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/publish_output
  displayName: 'Publish project'

# 5) Archive into zip
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/TaskManager.zip'
    replaceExistingArchive: true

# 6) Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'taskManager'
    appName: 'TaskManager'
    package: '$(Build.ArtifactStagingDirectory)/TaskManager.zip'


