# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master

pool:
  name: 'MyLocalAgent'
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactStagingDirectory)'
    zipAfterPublish: true # Questo crea il file zip per te

# 👇 Aggiungi questo task per il deploy
- task: AzureWebApp@1
  displayName: 'Deploy su Azure App Service'
  inputs:
    azureSubscription: 'taskManager'
    appName: 'TaskManager'
    package: '$(build.artifactStagingDirectory)/WebApp.zip'
