# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master

pool:
  name: MyLocalAgent   # <-- usa il tuo agent pool self-hosted

variables:
  buildConfiguration: 'Release'

steps:
# 1) Usa .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

# 2) Restore
- script: dotnet restore
  displayName: 'Restore dependencies'

# 3) Build
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build project'

# 4) Test (opzionale)
- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run tests'

# 5) Publish
- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish project'

  # 6) Zip
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/TaskManager.zip'
    replaceExistingArchive: true

# 6) Deploy su Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'taskManager'   # service connection che hai creato in DevOps
    appName: 'TaskManager'                     # il nome dell'App Service su Azure
    package: '$(Build.ArtifactStagingDirectory)/TaskManager.zip'


